version: '3.8'

services:
  eyetracker-app:
    build: .
    container_name: python_processor
    volumes:
      - ./Codes:/app/Codes
      - ./Datas:/app/Datas
      - ./Outputs:/app/Outputs
    stdin_open: true
    tty: true

  result-viewer:
    image: nginx:alpine
    container_name: result_server
    ports:
      - "8080:80"
    volumes:
      - ./Outputs:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
